# Generated by Django 4.0.5 on 2022-07-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=122)),
                ('weight', models.PositiveIntegerField(verbose_name='default=0')),
            ],
        ),
    ]
