# Generated by Django 4.0.5 on 2022-07-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='weight',
            field=models.CharField(max_length=122),
        ),
    ]
